== Before you start

I recommend using http://www.vogella.com/tutorials/JavaLibrary-OkHttp/article.html[OkHttp] instead of HttpClient for new applications.
OkHttp is extremely efficient and has a great API.
This tutorial is still here, so provide information about HttpClient for existing users.

[[httpclient]]
== Using the Apache HttpClient
	
The Apache HttpClient library allows to handling HTTP requests.
To use this library add a dependency to your Maven or Gradle build file.
You find the latest version here: https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient
	
You retrieve and send data via the `HttpClient` class.
An instance of this class can be created with `new DefaultHttpClient();`
	
`DefaultHttpClient` is the standard HttpClient and uses the `SingleClientConnManager` class to handle HTTP connections.
`SingleClientConnManager` is not thread-safe, this means that access to it via several threads will create problems.
	
The HttpClient uses a `HttpUriRequest` to send and receive data. 
Important subclass of `HttpUriRequest` are `HttpGet` and `HttpPost`.

You can get the response of the HttpClient as anInputStream.
	

