[[web_apps]]
== Exercise - Configuring Spring Boot for web based applications

=== Target

In the following exercises a issue reporting tool is created. With this tool users can submit issues they found on a website.

=== Configure

First, there are a few dependencies that need to be added to the example project. 
Such as: 

Thymeleaf:: Thymeleaf is a powerful template processing engine for the Spring framework. 
Spring Boot Devtools:: The Spring Boot Devtools provides an ensemble of very useful tools that enhance the development experience a lot. Such as Automatic recompiling upon saving and much more.
Data JPA:: coming soon

H2:: Database

To add these dependencies to your project, just open the `build.gradle` file in the root folder of the project and add the following to the section 'dependencies'. Then `Right Click > Gradle > Refresh Gradle Project`. 


[source, groovy]
----
	compile('org.springframework.boot:spring-boot-starter-thymeleaf')
	runtime('org.springframework.boot:spring-boot-devtools')
	compile('org.springframework.boot:spring-boot-starter-data-jpa')
	runtime('com.h2database:h2')
----

=== Validate

Start your application with `Right Click on your Project > Run As > Spring Boot App`. Since we have the `dev-tools` dependency added to project we can use it's `live-reload` functionality. This does not need any configuration and recompiles the application every time you save any file in the project. 

