== Exercise - Creating an entity data class

=== Target
In this exercise we will create a data class that contains all the relevant information, essentially representing an issue report from a user. 

=== Setup
Create a new class in the `com.vogella.example` package and name it `IssueReport`.

Add the `@Entity` annotation. This will tell the Spring framework that this is just a data class.
Also add the `@Table(name="issues")` annotation to the class. This later tells our database system to store the data in the table `issues`.

=== Adding fields to the entity data class

Add the following fields and a default constructor to the class:

[source, java]
----
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	private String email;
	private String url;
	private String description;
	private boolean markedAsPrivate;
	private boolean updates;
	private boolean done;
	private Date created;
	private Date updated;
	
	public IssueReport() {}
----

The values of the fields `email`, `url`, `description`, `markedAsPrivate` and `updates` will be coming from the form the user submitted. 
The others will be generated on creation or when the report is updated.

For better accessibility of the values it's good practice to use `getters` and `setters`.
To automatically generate them `Right Click` in the source code window of the `IssueReport` class. Then select the `Source` sub-menu; from that menu selecting `Generate Getters and Setters` will cause a wizard window to appear. 
Select the fields (in this case all) that you want `getters` and `setters` to be generated for. 
Confirm with ok.


=== Validation

Your `IssueReport` class should look like this:

[source, java]
----
package com.vogella.example;

import java.sql.Date;
import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class IssueReport {
	@Id
    private long id;
    private String email;
    private String url;
    private String description;
    private boolean markedAsPrivate;
    private boolean updates;
    private boolean done;
    private Date created;
    private Date updated;

    public IssueReport() {}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isMarkedAsPrivate() {
		return markedAsPrivate;
	}

	public void setMarkedAsPrivate(boolean markedAsPrivate) {
		this.markedAsPrivate = markedAsPrivate;
	}

	public boolean isUpdates() {
		return updates;
	}

	public void setUpdates(boolean updates) {
		this.updates = updates;
	}

	public boolean isDone() {
		return done;
	}

	public void setDone(boolean done) {
		this.done = done;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}
}

----

