== Exercise - Creating an entity data class

=== Target
In this exercise we will create a data class that contains all the relevant information, essentially representing an issue report from a user. 

=== Setup
Create a new class in the `com.vogella.example` package and name it `IssueReport`.

Add the annotation `@Data` from the `lombok` package above the class declaration. 

This will create `getter` and `setter` methods during compilation. 
This helps you write cleaner code as you don't have to declare them manually. 

TIP: If you want to use these methods before compilation you will need the `lombok` plugin. You can download it from https://projectlombok.org/download[projectlombok.org/download]. 

Also add the `@Entity` annotation. This will tell the Spring framework that this is just a data class.

=== Adding fields to the entity data class

Add the following fields and a default constructor to the class:

[source, java]
----

	private long id;
	private String email;
	private String url;
	private String description;
	private boolean markedAsPrivate;
	private boolean updates;
	private boolean done;
	private Date created;
	private Date updated;
	
	public IssueReport() {}


----

The fields `email`, `url`, `description`, `markedAsPrivate` and `updates` will be coming from the form the user submitted. The rest will be generated on creation or when the report is updated.



=== Validation

Your `IssueReport` class should look like this:

[source, java]
----

import java.util.Date;

import javax.persistence.Entity;

import lombok.Data;

@Data
@Entity
public class IssueReport {

	private long id;
	
	private String email;
	private String url;
	private String description;
	private boolean markedAsPrivate;
	private boolean updates;
	private boolean done;
	private Date created;
	private Date updated;
	
	public IssueReport() {}
	
}

----

