== Exercise - Creating an entity data class

=== Target
In this exercise we will create a data class that contains all the relevant information, essentially representing an issue report from a user. 

=== Setup
Create a new class in the `com.vogella.example` package and name it `IssueReport`.

Add the annotation `@Data` from the `lombok` package above the class declaration. 

This will create `getter` and `setter` methods during compilation. 

--JENNIFER: in my case the getter and setter where not created. What went wrong?

This helps you write cleaner code as you don't have to declare them manually. 

TIP: If you want to use these methods before compilation you will need the `lombok` plugin. You can download it from https://projectlombok.org/download[projectlombok.org/download]. 

Also add the `@Entity` annotation. This will tell the Spring framework that this is just a data class.

=== Adding fields to the entity data class

Add the following fields and a default constructor to the class:

[source, java]
----
	private long id;
	private String email;
	private String url;
	private String description;
	private boolean markedAsPrivate;
	private boolean updates;
	private boolean done;
	private Date created;
	private Date updated;
	
	public IssueReport() {}
----

The fields `email`, `url`, `description`, `markedAsPrivate` and `updates` will be coming from the form the user submitted. 
The rest will be generated on creation or when the report is updated.

=== Validation

Your `IssueReport` class should look like this:

[source, java]
----
package com.vogella.example;

import java.sql.Date;
import javax.persistence.Entity;
import javax.persistence.Id;
import lombok.Data;

@Data
@Entity
public class IssueReport {
	@Id
    private long id;
    private String email;
    private String url;
    private String description;
    private boolean markedAsPrivate;
    private boolean updates;
    private boolean done;
    private Date created;
    private Date updated;

    public IssueReport() {}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isMarkedAsPrivate() {
		return markedAsPrivate;
	}

	public void setMarkedAsPrivate(boolean markedAsPrivate) {
		this.markedAsPrivate = markedAsPrivate;
	}

	public boolean isUpdates() {
		return updates;
	}

	public void setUpdates(boolean updates) {
		this.updates = updates;
	}

	public boolean isDone() {
		return done;
	}

	public void setDone(boolean done) {
		this.done = done;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}
}

----

