== Exercise - Creating Templates using Thymeleaf

-- THIS NEEDS A LITTLE REWORK. ITS KINDA LATE SO YEAH --

Thymeleaf is a powerful template engine for the Spring framework. It lets you write clean HTML code while also using Java objects for data binding. You already added the Library to your project when you configured it in `3`.

=== HTML Templates

In the root folder of your project is another folder called `src/main/resources`. This contains all resources you need in your SpringBoot application. This is where we create our templates. Open the folder and create a new file called `issuereport_form.html` in it. This is the file that will be served on the route `/issuereport`. Create another file with the name `issuereport_list` in it. This file will be served on the `/issues` route. But to achieve this, we need to configure our controller to do so.

=== Serving HTML Templates
Currently all our controller methods have the `@ResponseBody`. With this annotation the data sent to the browser is plain text. If we remove it, the Thymeleaf library will look for an HTMLTemplate with the name returned. 

To configure Thymeleaf to do so we need to remove the `@ResponseBody` from all methods in the controller. We will also need to return the name of the template we want to serve on the given route. 
Return the following strings in the methods respectively:

getReport():: `issuereport_form`
submitReport():: `issuereport_form`
getIssues():: `issurereport_list`

Since we will want to pass data into the template we also need to add a `Model` to the methods parameters. 
Add `Model model` to the controller methods parameters. These will be automatically injected upon calling the method. Since this is fully done by the Spring framework we don't have to worry about this. What we can do is set attributes in the model or change its values. But we will get back to that.

The `RouteController` class should look like this:

[source, Java]
----

	@GetMapping("/issuereport")
	public String getReport(Model model) {
	
		return "issuereport_form";
	}
	
	@PostMapping(value="/issuereport")
	public String submitReport(Model model){
	
		return "issuereport_form";
	}
	
	@GetMapping("/issues")
	public String getIssues(Model model) {
	
		return "issuereport_list";
	}

----

Now the application will look for templates with the names a controller method returns. 

=== Binding objects to templates

Now you want to pass some data to the rendered page. This is done by adding an object and optionally a name to the `Model` object passed in by the Spring framework. Use the `addAttribute(...)` method for this.
As the first parameter you pass in a name for the object you pass in as the second parameter. You will use this name to refer to this object in the template. 

For the initial form route pass in an empty object of the data class you created in the previous exercise. 
Add `model.addAttribute("issuereport", new IssueReport());` to the method `getReport(...)`.

Repeat the same for the method `submitReport(...)`. 

In this method we also want to handle the data submitted via the form. To do this we also need to add `@ModelAttribute IssueReport issuereport` to the method parameters. 

NOTE: This will also be auto generated by the Spring framework. 

Since we want the template to show some kind of feedback upon receiving the form data, we should also add another attribute containing a boolean. If its set to `true` the template will show some kind of modal or confirming message. 

Just add another attribute with the name of `submitted` and the value `true`.

==== Validate
This method should now look like this:
[source, java]
----
	@PostMapping(value="/issuereport")
	public String submitReport(@ModelAttribute IssueReport issueReport, Model model) {
		IssueReport result = this.issueRepository.save(issueReport);
		model.addAttribute("submitted", true);
		model.addAttribute("issuereport", result);
		return "issuereport_form";
	}

----

Since we don't have any data to pass to the list view of the reports, we will leave it as it is for now.

=== Using the Data

To use the objects passed into the templates we need to use specific Thymeleaf HTML syntax. All properties and attributes in an HTML file will begin with `th:`.

We will start with the following basic HTML document with form in it:

[source, HTML]
----
<!DOCTYPE html>
<html>
<head>
	<title>Vogella Issuereport</title>
	<link rel="stylesheet" href="./style.css" />
	<meta charset="UTF-8" />
</head>
<body>
	<div class="container">
		<form method="post" action="#">
			<h3>Vogella Issuereport</h3>
			<input type="text" placeholder="Email" id="email"/> 
			<input type="text" placeholder="Url where the issue was found on" id="url"/>
			<textarea placeholder="Description of the issue" rows="5" id="description"></textarea>
			
			<label for="private_id">Private?</label>
			<input type="checkbox" name="private" id="private_id"/>
			
			<label for="updates_id">Keep me posted</label>
			<input type="checkbox" id="updates_id" name="updates"/>
			
			<input type="submit" value="Submit"/> 
		</form>
	
		<div class="result_message">
			<h3>Your report has been submitted.</h3>
			<p>Find all issues <a href="/issues">here</a></p>
		</div>
	</div>
</body>
</html>

----

This does not have any logic or data-binding in it and if you try to use this Spring will throw an exception. This is due to not telling Thymeleaf that this document should be handled as an HTMLTemplate. To achieve this we need to add `xmlns:th="http://www.thymeleaf.org"` to the `<html>` tag as an attribute. 

Now the file will be served on the route http://localhost:8080/issuereport[`/issuereport`]. If you have the application still running you can navigate to the route or click the link.

=== Data-binding

Now we want to tell Spring that this form should populate the fields of the `IssueReport` object we passed in earlier. This is done by adding `th:object="${issuereport}"` to the `<form>` tag.

NOTE: Remember that we set the name of the `IssueReport` object to `issuereport`? We refer to it now by using that name. The same can be done with any name and object.

This alone will not tell Spring to auto-populate the fields in the object. We need to specify in the `<input>` elements what field this should represent. This is done by adding the attribute `th:field="*{...}"` to the field while `...` is a placeholder for the name of the field inside the form-object. 

NOTE: `${...}` is the way to refer to objects that were passed to the template. `*{...}` is the syntax to refer to objects of these objects.

Add the following attributes to the `<input>` and `<textarea>` elements respectively.

`<input type="text" ... id="email"/>`:: `*{email}`
`<input type="text" ... id="url"/>`:: `*{url}`
`<textarea type="text" ... id="description"></textarea>`:: `*{description}`
`<input type="checkbox" name="private" ... />`:: `*{markedAsPrivate}`
`<input type="checkbox" name="updates" ... />`:: `*{updates}`

We also wanted to show some kind of confirmation modal upon submission. There already exists a modal for this in the template. The `<div class="result_message">`. But this should obviously be hidden if there was nothing to submit so everytime the user navigates to the site to submit an issue. This is done via a conditional expression. Namely `th:if="..."` with `...` being the expression. 

Remember that we passed in a boolean with the name `submitted` in the `submitReport(...)` method? This we will now use to determine if we should show the confirmation modal. 

Add `th:if="${submitted}"` to the `<div class="result_message">`. It will now show if the object with the name `submitted` is there and not `false`. Otherwise it will just not render the whole element and all its childs. 

=== Optional: Stylesheets

If you want to have some styling for the page, this snippet styles it a bit. This is optional and does not change the behavior of the application in anyway. It is already linked to page via the `<link ...>` element in the `<head>` section.
Create a new file in the `static` folder in `src/main/resources`. Name it `style.css` and copy the following snippet into it. Feel free to play around with it a little.

[source, CSS]
----
*{
	padding: 0;
	margin: 0;
	box-sizing: border-box;
}
body{
	font-family: sans-serif;
}
.container {
	width: 100vw;
	height: 100vh;
	padding: 100px 0;
	text-align: center;	
}
.container form{
	width: 100%;
	height: 100%;
	margin: 0 auto;
	max-width: 350px;
}
.container form input[type="text"], .container form textarea{
	width: 100%;
	padding: 10px;
	border-radius: 3px;
	border: 1px solid #b8b8b8;
	font-family: inherit;
	margin-bottom: 20px;
}
.container h3{
	margin-bottom: 20px;
}
.container form input[type="submit"]{
	max-width: 250px;
	margin: auto;
	display: block;
	width: 55%;
	padding: 10px;
	background: darkorange;
	border: 1px solid #b8b8b8;
	border-radius: 3px;
	margin-top: 20px;
	cursor: pointer;
}
.issue_list table{
	text-align: left;
	border-collapse: collapse;
	border: 1px #b8b8b8 solid;
	margin: auto;
}
.issue_list .desc{
	min-width: 500px;
}
.issue_list td, .issue_list th{
	border-bottom: 1px #b8b8b8 solid;
	border-top: 1px #b8b8b8 solid;
	padding: 5px;
}
.issue_list tr{
	height: 35px;
	transition: background .25s;
	
}
.issue_list tr:hover{
	background: #eee;
}
.issue_list .status.done:after{
	content: '✓';
}
----


=== Validate

Your HTMLTemplate with the name `issuereport_form.html` should look like this:

[source, HTML]
----
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<head>
	<title>Vogella Issuereport</title>
	<link rel="stylesheet" href="./style.css" />
	<meta charset="UTF-8" />
	
</head>
<body>

	<div class="container">
		<form method="post" action="#" th:action="@{/issuereport}" th:object="${issuereport}">
			<h3>Vogella Issuereport</h3>
			<input type="text" placeholder="Email" th:field="*{email}"/>
			<input type="text" placeholder="Url where the issue was found on" th:field="*{url}"/>
			<textarea placeholder="Description of the issue" rows="5" th:field="*{description}"></textarea>
			
			<label for="private_id">Private?</label>
			<input type="checkbox" name="private" id="private_id" th:field="*{markedAsPrivate}"/>
			
			<label for="updates_id">Keep me posted</label>
			<input type="checkbox" id="updates_id" name="updates" th:field="*{updates}"/>
			
			<input type="submit" value="Submit"/> 
		</form>
	
		<div class="result_message" th:if="${submitted}">
			<h3>Your report has been submitted.</h3>
			<p>Find all issues <a href="/issues">here</a></p>
		</div>
	</div>
</body>
</html>
----

Reload the page on the route `/issuereport`. Fill in the fields with some values and press submit. It should take you to the same page but this time the message `Your report has been submitted.` should show up. 


