== Exercise - Embedding a database

In this exercise you will learn how to use a database to store the users issues and query them to show them on the list view.

=== Setup

We will use the `h2` database for this. You already added this to your project in <<web_apps>>.
Spring Boot automatically picks up and configures `h2` when it's on the classpath. 

Now we only need to write a repository to interface with the db.

Create a new package called `com.vogella.example.repositories`. 
In here create a new `interface` with the name `IssueRepository`. 
This `interface` should extend the `interface` 'JpaRepository<>' from the package `org.springframework.data.jpa.repository`. 
Pass in `IssueReport` as the first parameter and `Long` as the second. 
This represents the object you are storing and the id it has inside the database.

Your `interface` should now look like this:

[source, java]
----
package com.vogella.example.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import com.vogella.example.IssueReport;

public interface IssueRepository extends JpaRepository<IssueReport, Long>{
}

----

This alone would already be enough to fetch all the entries from the database, add new entries and do all basic CRUD operations. 


But we want to fetch all entries which are not marked private and show them on the public list view.
This is done by adding a custom query string to a method.
Add this method to your `interface`

[source, java]
----
package com.vogella.example.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.JpaRepository;

import com.vogella.example.IssueReport;

public interface IssueRepository extends JpaRepository<IssueReport, Long>{
	@Query(value = "SELECT i FROM Issues i WHERE markedAsPrivate = false")
	List<IssueReport> findAllButPrivate();
----

NOTE: The annotation `@Query` lets us add custom JPQL queries that are executed upon calling the method. 

We also want to get all Issues reported by the same email-address. 
This is also done with a custom method. 
But for this we don't need a custom `@Query`. 
It's enough to create a method named `findAllByXXX`. `XXX` is a placeholder for the column you want to select by from the database.
The value for this is passed in as a method parameter.

Add the following to your `interface` as well:
[source, java]
----
package com.vogella.example.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.JpaRepository;

import com.vogella.example.IssueReport;

public interface IssueRepository extends JpaRepository<IssueReport, Long>{
	@Query(value = "SELECT i FROM Issues i WHERE markedAsPrivate = false")
	List<IssueReport> findAllButPrivate();
	
	List<IssueReport> findAllByEmail(String email);
}
----

=== Using the repository

Go back to your controller class `IssueController.java` and add a new field of the repository interface to the class. 
Since the @Controller is managed by Spring the `IssueRepository` will automatically be injected into the constructor.

[source, java]
----
package com.vogella.example.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

import com.vogella.example.IssueReport;
import com.vogella.example.repositories.IssueRepository;

@Controller
public class IssueController {
	IssueRepository issueRepository;

    public IssueController(IssueRepository issueRepositoy) {
        this.issueRepository = issueRepository;
    }
	
	@GetMapping("/issuereport")
	public String getReport(Model model) {
		model.addAttribute("issuereport", new IssueReport());
		return "issuereport_form";
	}

	@PostMapping(value="/issuereport")
    public String submitReport(@ModelAttribute IssueReport issueReport, Model model) {
		model.addAttribute("submitted", true);
		model.addAttribute("issuereport", new IssueReport());		
		return "issuereport_form";
    }
    
    @GetMapping("/issues")
    public String getIssues(Model model) {
        return "issuereport_list";
    }
}
----


==== Saving records to the database

To save a record to the database simply use the method `save()` from the `IssueRepository` interface and pass the object you want to store. 
In this case this is the received data on the path `/issuereport`. 

[source, java]
----
package com.vogella.example.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

import com.vogella.example.IssueReport;
import com.vogella.example.repositories.IssueRepository;

@Controller
public class IssueController {
	IssueRepository issueRepository;

    public IssueController(IssueRepository issueRepositoy) {
        this.issueRepository = issueRepository;
    }
	
	@GetMapping("/issuereport")
	public String getReport(Model model) {
		model.addAttribute("issuereport", new IssueReport());
		return "issuereport_form";
	}

	@PostMapping(value="/issuereport")
    public String submitReport(@ModelAttribute IssueReport issueReport, Model model) {
		IssueReport result = this.issueRepository.save(issueReport);
		model.addAttribute("submitted", true);
		model.addAttribute("issuereport", result);
		return "issuereport_form";
    }
    
    @GetMapping("/issues")
    public String getIssues(Model model) {
        return "issuereport_list";
    }
}
----

This saves the given object to the database and then returns the freshly saved object. 
In this case there is not much of a difference but this may vary if you use auto generated values.

==== Fetching all records from the database

Normally this would be done using `findAll()`. 
But in this case we don't want to include records that are marked as private and for this we created the method `findAllButPrivate()`. 

[source, java]
----
package com.vogella.example.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

import com.vogella.example.IssueReport;
import com.vogella.example.repositories.IssueRepository;

@Controller
public class IssueController {
	IssueRepository issueRepository;

    public IssueController(IssueRepository issueRepositoy) {
        this.issueRepository = issueRepository;
    }
	
	@GetMapping("/issuereport")
	public String getReport(Model model) {
		model.addAttribute("issuereport", new IssueReport());
		return "issuereport_form";
	}

	@PostMapping(value="/issuereport")
    public String submitReport(@ModelAttribute IssueReport issueReport, Model model) {
		IssueReport result = this.issueRepository.save(issueReport);
		model.addAttribute("submitted", true);
		model.addAttribute("issuereport", result);
		return "issuereport_form";
    }
    
    @GetMapping("/issues")
    public String getIssues(Model model) {
    	model.addAttribute("issues", this.issueRepository.findAllButPrivate());
       return "issuereport_list";
    }
}

----

=== Validate 

Your `IssueController` should now look like this: 
[source, java]
----
package com.vogella.example.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

import com.vogella.example.IssueReport;
import com.vogella.example.repositories.IssueRepository;

@Controller
public class IssueController {
	IssueRepository issueRepository;

    public IssueController(IssueRepository issueRepositoy) {
        this.issueRepository = issueRepository;
    }
	
	@GetMapping("/issuereport")
	public String getReport(Model model) {
		model.addAttribute("issuereport", new IssueReport());
		return "issuereport_form";
	}

	@PostMapping(value="/issuereport")
    public String submitReport(@ModelAttribute IssueReport issueReport, Model model) {
		IssueReport result = this.issueRepository.save(issueReport);
		model.addAttribute("submitted", true);
		model.addAttribute("issuereport", result);
		return "issuereport_form";
    }
    
    @GetMapping("/issues")
    public String getIssues(Model model) {
    	model.addAttribute("issues", this.issueRepository.findAllButPrivate());
        return "issuereport_list";
    }
}

----

The `IssueRepository` should look like this:
[source, java]
----
package com.vogella.example.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.JpaRepository;

import com.vogella.example.IssueReport;

public interface IssueRepository extends JpaRepository<IssueReport, Long>{
	@Query(value = "SELECT i FROM Issues i WHERE markedAsPrivate = false")
	List<IssueReport> findAllButPrivate();
	
	List<IssueReport> findAllByEmail(String email);
}
----

Go ahead and reload the form and enter some data.
Now click `submit` and go to the route http://localhost:8080/issues[`/issues`]. You should see the previously entered data.

