== Exercise: Create a User domain model

Create another package called _com.vogella.spring.user.domain_ and create a _User_ class inside it.

[source, java]
----
package com.vogella.spring.user.domain;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data <1>
@NoArgsConstructor <2>
@AllArgsConstructor <3>
@Builder <4>
@JsonIgnoreProperties(ignoreUnknown = true) <5>
public class User {

	private long id;
	
	@Builder.Default <6>
	private String name = "";
	
	@Builder.Default
	private String email = "";
	
	@Builder.Default
	private String password = "";
	
	@Builder.Default
	private List<String> roles = new ArrayList<>();
	
	@Builder.Default
	private Instant lastLogin = Instant.now();
	
	private boolean enabled;
	
	public User(long id) {
		this.id = id;
	}
}
----

<1> The _User_ class is a simple data class and the _@Data_ annotation of the Lombok library automatically generates getters and setters for the properties and _hashCode()_, _equals()_ and _toString()_ methods.
<2> If a certain constructor is implemented and a constructor with no arguments should still be available the _@NoArgsConstructor_ annotation can be used.
<3> This is a convenience annotation to provide a constructor with all available field automatically
<4> This annotation automatically generates a Builder for a class. Usually used for classes with many field, that may have default values.
<5> The User is also supposed to be serialized and deserialized with JSON, Spring uses the Jackson library for this by default. @JsonIgnoreProperties(ignoreUnknown = true) specifies that properties, which are available in the JSON String, but not specified as class members will be ignored instead of raising an Exception.
<6> The `@Builder.Default` annotation tells Lombok to apply these default values, if nothing else will be set during the creation of a User object 

