== Exercise: Creating a service for the business logic

Creating an initial model should not be part of the `UserRestController` itself.
A rest controller should simply specify the rest API and then delegate to a service, which handles the business logic in behind.

Therefore a `UserService` class should be created in the _com.vogella.spring.user.service package.

[source, java]
----
package com.vogella.spring.user.service;

import java.time.Instant;
import java.util.Collections;

import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

import com.vogella.spring.user.domain.User;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

@Service
public class UserService {

	private Flux<User> users;

	public UserService() {
		users = createUserModel();
	}

	private Flux<User> createUserModel() {
		User user = new User(1, "Fabian Pfaff", "fabian.pfaff@vogella.com", "sdguidsdsghuds",
				Collections.singletonList("ADMIN"), Instant.now(), true);
		User user2 = new User(1, "Simon Scholz", "simon.scholz@vogella.com", "sdguidsdsghuds",
				Collections.singletonList("ADMIN"), Instant.now(), false);
		User user3 = new User(1, "Lars Vogel", "lars.vogel@vogella.com", "sdguidsdsghuds",
				Collections.singletonList("USER"), Instant.now(), true);

		return Flux.just(user, user2, user3);
	}

	public Flux<User> getUsers(@RequestParam(name = "limit", required = false, defaultValue = "-1") long limit) {
		if (-1 == limit) {
			return users;
		}
		return users.take(limit);
	}

	public Mono<User> getUserById(@PathVariable("id") long id) {
		return Mono.from(users.filter(user -> id == user.getId()));
	}

	public Mono<User> newUser(@RequestBody User user) {
		Mono<User> userMono = Mono.just(user);
		users = users.mergeWith(userMono);
		return userMono;
	}

	public Mono<Void> deleteTodo(@PathVariable("id") int id) {
		users = users.filter(user -> user.getId() != id);
		return users.then();
	}
}
----

<1> The @Service annotation specifies this `UserService` as spring service, which will be created when it is demanded by other classes like the refactored `TodoRestController`.

Basically we just moved everything into another class, but left out the rest controller specific annotations.

Now the `UserRestController` looks clearly arranged and just delegates the rest requests to the `UserService`.

[source, java]
----
package com.vogella.spring.user.controller;

import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.vogella.spring.user.domain.User;
import com.vogella.spring.user.service.UserService;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

@RestController
@RequestMapping("/user")
class UserRestController {

	private UserService userService;

	public UserRestController(UserService userService) {
		this.userService = userService;
	}

	@GetMapping
	public Flux<User> getUsers(@RequestParam(name = "limit", required = false, defaultValue = "-1") long limit) {
		return userService.getUsers(limit);
	}

	@GetMapping("/{id}")
	public Mono<User> getUserById(@PathVariable("id") long id) {
		return userService.getUserById(id);
	}

	@PostMapping
	public Mono<User> newUser(@RequestBody User user) {
		return userService.newUser(user);
	}

	@DeleteMapping("/{id}")
	public Mono<Void> deleteTodo(@PathVariable("id") int id) {
		return userService.deleteTodo(id);
	}
}
----

<1> Since the Spring framework instantiates the `UserRestController` it is able to find the `UserService`, which is demanded in the `UserRestController` constructor. This works, because the `UserService` class has the `@Service` annotation being applied.

The `UserService` will do more stuff in the upcoming chapters.

