== Exercise: Creating a service for the business logic

Creating an initial model should not be part of the `TodoRestController` itself.
A rest controller should simply specify the rest API and then delegate to a service, which handles the business logic in behind.

Therefore a `TodoService` class should be created in the com.vogella.springboot2.service package.

[source, java]
----
package com.vogella.springboot2.service;

import org.springframework.stereotype.Service;

import com.vogella.springboot2.domain.Todo;

import reactor.core.publisher.Flux;

@Service #<1>
public class TodoService {

	private Flux<Todo> todos;

	public TodoService() {
		todos = createTodoModel();
	}

	private Flux<Todo> createTodoModel() {
		Todo todo = new Todo(1);
		todo.setSummary("Learn Spring Boot 2.0");
		todo.setDescription("Easily create modern reactive webapps with Spring Boot 2.0");

		Todo todo2 = new Todo(2);
		todo2.setSummary("Learn Reactor Framework");
		todo2.setDescription("Use the power of the reactive io api with the Reactor Framework");

		Todo todo3 = new Todo(3);
		todo3.setSummary("Learn @RestController");
		todo3.setDescription("Learn how to create @RestController and use rest endpoints");

		return Flux.just(todo, todo2, todo3);
	}

	public Flux<Todo> getTodos(long limit) {
		if (-1 == limit) {
			return todos;
		}
		return todos.take(limit);
	}

	public Mono<Todo> getTodoById(long id) {
		return Mono.from(todos.filter(t -> id == t.getId()));
	}

	public Mono<Todo> newTodo(Todo todo) {
		Mono<Todo> todoMono = Mono.just(todo);
		todos = todos.mergeWith(todoMono);
		return todoMono;
	}

	public Mono<Void> deleteTodo(int id) {
		todos = todos.filter(todo -> todo.getId() != id);
		return todos.then();
	}
}

----

<1> The @Service annotation specifies this `TodoService` as spring service, which will be created when it is demanded by other classes like the refactored `TodoRestController`.

Basically we just moved everything into another class, but left out the rest controller specific annotations.

Now the `TodoRestController` looks clearly arranged and just delegates the rest requests to the `TodoService`.

[source, java]
----
package com.vogella.springboot2.controller;

import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.vogella.springboot2.domain.Todo;
import com.vogella.springboot2.service.TodoService;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

@RestController
class TodoRestController {
	
	private TodoService todoService;

	public TodoRestController(TodoService todoService) { #<1>
		this.todoService = todoService;
	}

	@GetMapping("/getTodos")
	public Flux<Todo> getTodos(@RequestParam(name = "limit", required = false, defaultValue = "-1") long limit) {
		return todoService.getTodos(limit);
	}

	@GetMapping("/getTodoById")
	public Mono<Todo> getTodoById(long id) {
		return todoService.getTodoById(id);
	}

	@PostMapping("/newTodo")
	public Mono<Todo> newTodo(@RequestBody Todo todo) {
		return todoService.newTodo(todo);
	}

	@DeleteMapping("/deleteTodo/{id}")
	public Mono<Void> deleteTodo(@PathVariable("id") int id) {
		return todoService.deleteTodo(id);
	}
}

----

<1> Since the Spring framework instantiates the `TodoRestController` it is able to find the `TodoService`, which is demanded in the `TodoRestControllers` constructor. This works, because the `TodoService` class has the `@Service` annotation being applied.

The `TodoService` will do more stuff in the upcoming chapters.

