== Exercise: Reactive database access with Spring Data

Using reactive Reactor types like `Flux<T>` is really nice and powerful, but keeping the User data in-memory is not.

In former chapters, where the project has been created MongoDB dependencies have already been selected.

[NOTE]
====
MongoDB has the benefit that it comes with a reactive database driver, which other databases like JDBC cannot offer. Hopefully in the future other databases catch up and provide reactive asynchronous database drivers as well.
====

But don't be scared, if you haven't used MongoDB yet, because there is a `compile('org.springframework.boot:spring-boot-starter-data-mongodb-reactive')` dependency in your _build.gradle_ file, which provides an abstraction layer around the database.

In order to find, save and delete `User` objects in the MongoDB a `UserRepository` in the _com.vogella.spring.user.data_ package should be created.

[source, java]
----
package com.vogella.spring.user.data;

import org.springframework.data.repository.reactive.ReactiveCrudRepository;

import com.vogella.spring.user.domain.User;

public interface UserRepository extends ReactiveCrudRepository<User, Long> {

}
----

Now Spring can create a `ReactiveCrudRepository` for `User` objects at runtime automatically, which provides (C)reate, (R)ead, (U)pdate and (D)elete capabilties.

[NOTE]
====
The `ReactiveCrudRepository` class is similar to Spring Datas' `CrudRepository` class, but is able to return reactive asynchronous types rather than synchronous types.
====

Now we have to enable MongoDB to work with `User` objects:

[source, java]
----
package com.vogella.spring.user.domain;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

import org.springframework.data.annotation.Id;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@JsonIgnoreProperties(ignoreUnknown = true)
public class User {

	@Id
	private long id;
	@Builder.Default
	private String name = "";

	@Builder.Default
	private String email = "";

	@Builder.Default
	private String password = "";

	@Builder.Default
	private List<String> roles = new ArrayList<>();

	@Builder.Default
	private Instant lastLogin = Instant.now();

	private boolean enabled;
	
	public User(long id) {
		this.id = id;
	}

}
----

<1> @Id is used to specify the id of the object, which is supposed to be stored in the database

Now the `UserService` should be updated to store the data by using the `UserRepository`.

[source, java]
----
package com.vogella.spring.user.service;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collections;

import org.springframework.stereotype.Service;

import com.vogella.spring.user.data.UserRepository;
import com.vogella.spring.user.domain.User;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

@Service
public class UserService {

	private UserRepository userRepository;

	public UserService(UserRepository UserRepository) { <1>
		this.userRepository = UserRepository;
		createUserModel();
	}

	private void createUserModel() {
		User user = new User(1, "Fabian Pfaff", "fabian.pfaff@vogella.com", "sdguidsdsghuds",
				Collections.singletonList("ADMIN"), Instant.now(), true);
		User user2 = new User(1, "Simon Scholz", "simon.scholz@vogella.com", "sdguidsdsghuds",
				Collections.singletonList("ADMIN"), Instant.now(), false);
		User user3 = new User(1, "Lars Vogel", "lars.vogel@vogella.com", "sdguidsdsghuds",
				Collections.singletonList("USER"), Instant.now(), true);

		userRepository.saveAll(Arrays.asList(user, user2, user3)).subscribe(); <2>
	}

	public Flux<User> getUsers(long limit) {
		if (-1 == limit) {
			return userRepository.findAll();
		}
		return userRepository.findAll().take(limit);
	}

	public Mono<User> findUserById(long id) {
		return userRepository.findById(id);
	}

	public Mono<User> newUser(User User) {
		return userRepository.save(User);
	}

	public Mono<Void> deleteUser(long id) {
		return userRepository.deleteById(id);
	}
}
----

<1> Even tough the `UserRepository` interface is not annotated with @Service, @Bean, @Component or something similar it is automatically injected. The Spring Framework creates an instance of the `UserRepository` at runtime once it is requested by the `UserService`, because the `UserRepository` is derived from `ReactiveCrudRepository`.

<2> For the initial model the 3 Users from former chapters are now stored in the MongoDB.

For all other operations the `ReactiveCrudRepository` default methods, which return Reactor types, are used (`findAll`, `findById`, `save`, `deleteById`).

