== Validations with JSR-303

So far the `UserController` accepts any input for a new user entity.
To stop clients to create entities with invalid data we can add validations.
Java provides a way to define validation rules by placing @annotations on fields.

The user object must only be created when a valid email and password have been provided:

[source, java]
----
package com.vogella.spring.user.domain;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Size;

import org.springframework.data.annotation.Id;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@JsonIgnoreProperties(ignoreUnknown = true)
public class User {

	@Id
	private long id;
	@Builder.Default
	private String name = "";

	@NotEmpty
	@Email
	@Builder.Default
	private String email = "";

	@Size(min = 8, max = 254)
	@Builder.Default
	private String password = "";

	@Builder.Default
	private List<String> roles = new ArrayList<>();

	@Builder.Default
	private Instant lastLogin = Instant.now();

	private boolean enabled;
	
	public User(long id) {
		this.id = id;
	}

}
----

To tell Spring that it should run the validations in the controller we have to add a `@Valid` annotation to the incoming data:

[source, java]
----
	@PostMapping
	public Mono<ResponseEntity<Object>> newUser(@RequestBody @Valid Mono<User> userMono, ServerHttpRequest req) {
		return userMono.flatMap(user -> {
			return userService.newUser(user)
					.map(u -> ResponseEntity.created(URI.create(req.getPath() + "/" + u.getId())).build());
		});
	}
----

Now try to create a user like we've done in a former exercise and see what happens:

[source, curl]
----
curl -d '{"id":100, "name":"Spiderman"}' -H "Content-Type: application/json" -X POST http://localhost:8080/user
----

This time the response contains a 400 error code and complains about the invalid email and password field.

Therefore the request has to be updated to include a valid email adress and password.

[source, curl]
----
curl -d '{"id":100, "name":"Spiderman", "email":"me@spidey.com", "password":"WithGreatPowerComesGreatResponsibility"}' -H "Content-Type: application/json" -X POST http://localhost:8080/user
----

This time the _Spiderman_ user is successfully added to the list of users, which can be verified by navigating to http://localhost:8081/user.

