[[programminginjavascript]]
== Appendix - Programming in JavaScript

[[javascript_variables]]
=== Variables and data types

The following example demonstrates how to declare and use variables in JavaScript.
You may notice that there are several ways of declaring variables.

[source, javascript]
----
let mytext= "Hello, hello. Turn the radio on. Is there anybody out there...";

/* declare variables t o do some math*/
a = 5; // global variable avoid this
let b = 1;
let result = a - b;

/* concatenate two strings*/
let mytext1 = "I like Spanish";
let mytext2 = " because the melody is nice.";
document.writeln(mytext1 + mytext2);
----


[WARNING]
====
JavaScript allows you to declare a variable without a keyword.
This creates global variables, which can lead to hard to determine bugs.
You should avoid them.
Also the  `var` keyword allows to define a variable but allows you to re-declare it, which can also lead to suble bugs.
The `let` keyword avoids this, by enforcing that a variable is only declared once.
With the `const` keyword it is possible to enforce that a variable can not be reassigned.
This doesn't mean that the variable is immutable, just that the reference can't change.
====
	
Variables defined without the keyword `var` are global variables.
Variables defined with `var` are scoped according to their declaration, e.g., if you define a `var` in a function this variable is only valid in the current function body.
Variables defined with `let` and `const` are only valid in the current block.

It is good JavaScript practice to always use one of the keywords to avoid global variables.

JavaScript has four basic types, _Object_ and the primitive types _Number_, _String_, and _Boolean_.
While Objects are passed by reference, the primitive types are passed by value.

[[javascript_string]]
=== String operations

You can define string and concatenate them.
The following example assumes you have two variables `user` and `validationError`.

[source, javascript]
----
var message = "Invalide user action for " + user.firstName + " " + user.lastName + 
  ". Operations ended with " + validationError;
----

Alternatively, can you also use the backtick string literal to allow string interpolation.

[source, javascript]
----
var message = `Invalide user action for ${user.firstName} ${user.lastName}.  Operations ended with ${validationError}`;
----


[[javascript_arrays]]
=== Arrays

Arrays are Objects in JavaScript. 
You can define them and use the method pop() to remove the first element and push(newValue) to add a new element at the end.
You can also iterate over it.

[source, javascript]
----
include::res/javascript/array.txt[]
----

[[javascript_functions]]
=== Functions

A function in JavaScript encapsulates reusable code and is represented as an Object. 
Functions can be directly called via other JavaScript code. 
It is recommended that you put functions in the header of the HTML page. 
Functions are declared via the function keyword. 
You can call a function directly, or use the apply method on the function.

[source, javascript]
----
include::res/function/function1.html[]
----

[[javascript_prototype]]
=== Prototype in JavaScripts

JavaScript does not support classes and inheritance of classes like object orientated programming languages. 
JavaScript is a prototype-based language, by this approach you can reuse functions by cloning existing objects.  

[[javascript_buttons]]
=== Assigning functions to HTML buttons

The following gives an example how to assign a function to an HTML button.

[source, javascript]
----
include::res/function/function.html[]
----

[[javascript_events]]
=== HTML Events

JavaScript can react to certain events on the page and be registered with webpage elements, e.g. buttons. 
You can register a function to an event in the HTML page. 


.Table Events in Javascript
|===
|Event |Description

|Onload
|Triggered when the user loads the page. The onload event can for example be used to check the visitors browser type.

|onChange
|Called whenever a field is changed. Can for example be used to validate an input field of a form.

|onSubmit
|Called when a user clicks on the submit button of a form.

|OnMouseOver and OnMouseOut
|Called when the mouse enters a certain element on the page or leaves it.
|===

