[[implementation]]
== Implementation Steps

[[implementation_applicationserver]]
=== Application Server Registration

The application server needs to authenticate himself with
the
C2DM servers. Via an email and password an authentication
token
is
determined with an HTTP POST request to the C2DM servers. The token
is stored on
the
application server and is
used to authenticate the
application
server
with the C2DM
servers once he sends out messages.

For example you can get the token for an registered email and password via the following coding:

[source,java]
----
include::res/server/AuthenticationUtil.java[]
----

The token is periodically refreshed.

The above example is in Java. It is also possible to get the
token via other http tools or programming languages. For
example you
can simulate the server via the command line tool with
the tool
curl.

[[implementation_mobileregistration]]
=== Getting the registration ID for the mobile app

To register your Android app for the C2DM service you fire an
registration intent
"com.google.android.c2dm.intent.REGISTER". This
will trigger a service which will send the registration to the Google
C2DM
servers.

The
intent include an extra with the key "sender" and the email
address which was registered for the C2DM service. It also must
include PendingIntent
with the "app" extra. The
PendingIntent gives the
Android system
information about the current
application. The value for
the "sender"
is the email address under which you registered your C2DM
message
service. Replace in the following example "youruser@gmail.com"
which your email address.

[source,text]
----
include::res/register/sendregister.txt[]
----

The service will asynchronously register with Google and will
send the "com.google.android.c2dm.intent.REGISTRATION" intent upon
successful registration. Your
application need to register an
Broadcast Receiver for this intent. This also requires the usage of a
permission based on your package as the Android system checks this
internally.

[source,java]
----
include::res/register/C2DMRegistrationReceiver.java[]
----

The ""AndroidManifest.xml looks like the following. Please note
that if you are using a different package that you have to adjust
this coding.

[source,xml]
----
include::res/register/AndroidManifest.xml[]
----

The "com.google.android.c2dm.intent.REGISTRATION" intent
includes a
registration
ID. Each registration ID
represents a particular
device,
e.g. every
Android phone will receive
its own registration code.

The C2DM may refresh this registration ID periodically but
until a refreshment your application should store this ID for later
use.

After the Android app received the registration
ID it
has to send
this information to the application server. The application server
can use the registration ID to send a message to the device via the
C2DM servers from Google.

For example the following code sends the deviceId and the
registrationId to a server.

[source,text]
----
include::res/register/sendToServer.txt[]
----

The
server
uses some persistence to store the registration IDs.

[[c2dm_registermessage]]
=== Register Receiver for C2DM messages

Similar to registration of the registration receiver you need
to configure a message receiver. This could be the same or a
different receiver then the registration receiver. The following
shows
an example of an separate message receiver.

[source,java]
----
include::res/register/C2DMMessageReceiver.java[]
----

In addition you need to register the message receiver in your `AndroidManifest.xml` file.

[source,text]
----
include::res/register/messagereceiver.txt[]
----

[[c2dm_sendmessage]]
=== Send messages

At this point your application server and your Android app are
ready to use C2DM. Your server has his authentication token and the
registration ID of the app. And the mobile app has registered
Broadcast Receiver for receiving the message.

To send a message to a device, the application server sends a
HTTP POST request to the Google
C2DM servers. This HTTP GET request
contains the registration ID for this device and well as
the
authentication token (to
tell Google that this server is allowed
to
send messages).

[source,java]
----
include::res/server/MessageUtil.java[]
----

Once your server sends the message to the C2DM server this
server will queue the message until the device is available. The
message will be send to the device as a broadcast. Your application
needs to register for this broadcast event to receive the message.

A received message is send to the registered broadcast receiver
for "com.google.android.c2dm.intent.RECEIVE".
The data can be
received
from
the Intent via getExtras(). The available keys are
"payload",
"from",
"collapse_key". The actual data is included in
"payload". The
receiver can extracts this data and can react
to it.

