== Exercise - Spring DI Autowire Beans

=== Target

Let the beans get their dependencies themselves. Until now only the no arg constructor and an explicitly created `Todo` where used.

But Beans themselves can also get their dependencies from Spring's DI Container.

=== Using the @Autowired Annotation

The `Todo` 's constructor can also be annotated with the `@Autowired` annotation.

By doing this and readding the `@Component` annotation to the `Todo` Spring will try to use the constructor with parameters, which are available in the Spring DI container.

[source, Java]
----
include::res/TodoAutowired.java[]
----

Now all constructor parameters have to be available so that `@Autowired` can work properly.

Optionally also the setter methods, e.g., dueDate and done, can be provided.

[source, Java]
----
include::res/ConfigAutowire.java[]
----

=== Validate

With this approach the `Todo` instance will be created by Spring again, but rather with the `@Autowired` constructor than the no arg constructor.

The `@Autowired` is also used for some of the setter methods.

NOTE: Setter injection should always be preferred, since classes that use field injection usually cannot be tested properly.


