== Exercise - Configure Webpack and use Babel

=== Target

Webpack is a tool to assemble several different JavaScript packages into one build artifact, e.g., _build/bundle.js_ file.
Babel can be used to transpile ES6 to ES5 or even react's jsx to JavaScript, so one can write new code, but still run it in older browsers.

=== Create a simple JavaScript file

Inside the _/src/main/resources/static_ directory a simple _app.js_ JavaScript file should be provided.

[source, javascript]
----
document.write("Hello first JavaScript sample!");
----

This _app.js_ script can be built by Webpack.

=== Configure Webpack

Webpack can be configured by a _webpack.config.js_, which basically also just exposes a configuration closure as module.

[source, javascript]
----
include::res/js/webpack.config.js[]
----

The previously defined _app.js_ script is know being transpiled by Babel if necessary and then packaged into a _bundle.js_ file as output.

=== Using Gradle to run Webpack

Create a _build.gradle_ file inside the _/src/main/resources/static_ directory of the project.

[source, groovy]
----
include::res/js/build.gradle[]
----

Afterwards go into the _static_ directory in the command line and run the `gradle webpack` task.

This will build the a _bundle.js_ script file, which has been specified as output in the _webpack.config.js_ configuration.

=== Using the built bundle.js script

In order to make use of the built _bundle.js_ file a `<script>` tag has to be added.

[source, html]
----
include::res/js/index-script.html[]
----

=== Validate

Start the Spring application, go to `http://localhost:8080` and see wheter the input equals ___Hello first JavaScript sample!___

NOTE: The big benefit here is that the _bundle.js_ script can be referenced by the HTML page and under the hood the _bundle.js_ script can always be regenerated by using Webpack.

