[[xml_overview]]
== XML Introduction

[[xml_overview_s2a]]
=== XML Overview

XML is the abbreviation for _Extensible Markup Language_ and is an established data exchange format. 
XML was defined 1998 by the World Wide Web Consortium (W3C).

An XML document consists of elements, each element has a start tag, content and an end tag.
An XML document must have exactly one root element (i.e., one tag which encloses the remaining tags). 
XML differentiates between capital and non-capital letters.

An XML file must be _well-formed_.
This means that it must apply to the following conditions:

* An XML document always starts with a prolog (see below for an explanation of what a prolog is)
* Every opening tag has a closing tag.
* All tags are completely nested.

An _valid_ XML file is well-formed and must contain a link to an XML schema and be valid according to that schema.


The following is a valid, well-formed XML file.

[source,xml]
----
include::res/xmlintro/firstxmlfile.txt[]
----

[[xml_comparisionwithotherformats]]
=== Comparison of XML to other formats

It is relatively easy to process an XML document, compared with a binary or unstructured format.
This is because of the following characteristics:

* XML is plain text
* XML represents data without defining how the data should be displayed
* XML can be transformed into other formats via XSL
* XML can be easily processed via standard parsers
* XML files are hierarchical

The XML format is relatively verbose, i.e., if data is represented as XML the size of this data is relatively large compared to other formats.
In the Internet JSON or binary formats are frequently used to replace XML if the data throughput is important.


[[xml_overview_s2c]]
=== XML Elements

An XML document always starts with a `prolog` which describes the XML file.
This prolog can be minimal, e.g. `<?xml version="1.0"?>`.
It can also contain other information, e.g. the encoding `<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>`.

A tag which does not enclose any content is know as an "empty tag", for example `<flag/>`.

Comments in XML are defined as: <! COMMENT>.

