[[jdbc_usage]]
== Using Spring JDBC template
	 
The following example will demonstrate the usage of the JDBC template. 
The example is based on derby.

[[jdbc_usage_db]]
=== Create Database
		
Create a small derby database under c:\temp\databases\test01 with the table "Person". 
Please see http://www.vogella.com/tutorials/EclipseDataToolsPlatform/article.html[Handling Database with the Eclipse Data Tools Project] for an explanation on how to do this with the Eclipse Data Tools Project.
		
Create the table Person with the following SQL statement.
		
[source,java]
----
include::res/createPersonTable.sql[]
----
		
[[jdbc_usage_javaproject]]
=== Create Java Project and domain model

Create a new Java project "de.vogella.spring.jdbctemplate" and include the minimal required jars into your classpath. 
Add also derby.jar to the classpath.
Create the following domain model.
		
[source,java]
----
include::res/Person.java[]
----

[[jdbc_usage_daointerface]]
=== Create the Data Access Object (DAO)Interface

Although not required it is always a good idea to program against an interface. 
Create the following DAO interface.
	
		
[source,java]
----
include::res/IDao.java[]
----

[[jdbc_usage_dao]]
=== Create the Dao with the JDBC Template

Now you can create the Dao using the JDBC Template function.
	
		
[source,java]
----
include::res/PersonResultSetExtractor.java[]
----
		
[source,java]
----
include::res/PersonRowMapper.java[]
----
		
[source,java]
----
include::res/DerbyDao.java[]
----

[[jdbc_usage_testing]]
=== Main program (for testing)

Finally create the following test class for testing your Spring Jdbc Template.
		
[source,java]
----
include::res/Main.java[]
----		

Run the main program in class Main to see the result.

