[[jaxb]]
== RESTful web services and JAXB

JAX-RS supports the automatic creation of XML and JSON via JAXB. 
For an introduction into XML please see http://www.vogella.com/tutorials/JavaXML/article.html[Java and XML - Tutorial]. 
For an introduction into JAXB please see http://www.vogella.com/tutorials/JAXB/article.html[JAXB]. 
You can continue this tutorial without reading these tutorials, but they contain more background information.

[[jaxb_project]]

[[firstjersey_project]]
=== Create new Gradle project

Create a new Gradle project named _com.vogella.jersey.jaxb_ with _com.vogella.jersey.jaxb_ as the top-level package name and configure Eclipse WTP.
You can follow <<projectsetup>> to get started.
To enable JSON support, add the following dependency to your _build.gradle_ file.
The second line automatically adds support for the media type `application/json`.
 
[source,java]
----
compile 'org.glassfish.jersey.containers:jersey-container-servlet:2.25.1'
compile 'org.glassfish.jersey.media:jersey-media-json-jackson:2.25.1'
----

[[jaxb_domainmodel]]
=== Create Java classes

Create your domain class.

[source,java]
----
include::res/jaxb/Todo.java[]
----

Create the following resource class. 
This class simply returns an instance of the `Todo` class.

[source,java]
----
include::res/jaxb/TodoResource.java[]
----

Change `web.xml` to the following.

[source,xml]
----
include::res/jaxb/web.xml[]
----

Run you web application in Eclipse and validate that you can access your service. 
Your application should be available under the following URL.

[source,text]
----
include::res/links/todo1.txt[]
----

[[jaxb_client]]
=== Create a client

Create a new Java Gradle project with _com.vogella.jersey.jaxbclient_ as top-level package name and add the following dependencies to your build.gradle file to import the Jersey dependencies and enable JSON support.
 
[source,text]
----
compile 'org.glassfish.jersey.containers:jersey-container-servlet:2.25.1'
compile 'org.glassfish.jersey.media:jersey-media-json-jackson:2.25.1'
----

Create the following test class.

[source,java]
----
include::res/jaxb/TodoTest.java[]
----